spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productandcategory
    username: root
    password: root
  liquibase:
    enabled: true
    drop-first: false
    change-log: db/changelog/migration.xml